### ISSUE TITLE
Relative path to test assembly not found (on osx, linux specifically?)

### ISSUE THREAD

**Issue by timbarrass** [joaoopereira/dotnet-test-rerun#127]
For reference, I'm running on OSX. If I try and use a relative path for my test assembly I get:

```
➜  net6.0 git:(feature/DEV-14338) test-rerun ./MyTest.dll -d 1
  Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (arm64)
  The test source file "/./MyTest.dll" provided was not found.
```

If I specify a full path I get :

```
➜  net6.0 git:(feature/DEV-14338) test-rerun /Users/tim/Documents/code/some/full/path/bin/Debug/net6.0/MyTest.dll -d 1
  Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (arm64)
  Copyright (c) Microsoft Corporation.  All rights reserved.

  Starting test execution, please wait...
```

**Comment by MarcinFrankowski** [comment]
I've had the same issue on 1.8.0. Also applies to the `--settings` parameter

**Comment by claasd** [comment]
I can confirm the same für search pathes, e.g. **/*MyTests.dll.
Does work perfectly well on a windows build agent, does not work on a linux build agent (ubuntu 22).
Command: 
```
dotnet tool install --global dotnet-test-rerun
STAGE=dev test-rerun **/*IntegrationTests.dll  -v normal --logger trx
```
Error:
```
Microsoft (R) Test Execution Command Line Tool Version 17.8.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Unhandled exception. System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Path.GetFullPath(String path)
   at System.IO.DirectoryInfo..ctor(String path)
   at vstest.console.Internal.FilePatternParser.GetMatchingFiles(String filePattern) in /_/src/vstest.console/Internal/FilePatternParser.cs:line 81
   at Microsoft.VisualStudio.TestPlatform.CommandLine.CommandLineOptions.AddSource(String source) in /_/src/vstest.console/CommandLine/CommandLineOptions.cs:line 283
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.ArgumentProcessorFactory.<>c__DisplayClass18_0.<WrapLazyProcessorToInitializeOnInstantiation>b__0() in /_/src/vstest.console/Processors/Utilities/ArgumentProcessorFactory.cs:line 282
   at System.Lazy`1.CreateValue()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.GetArgumentProcessors(String[] args, List`1& processors) in /_/src/vstest.console/CommandLine/Executor.cs:line 283
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[] args) in /_/src/vstest.console/CommandLine/Executor.cs:line 173
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Program.Main(String[] args) in /_/src/vstest.console/Program.cs:line 22



Unhandled exception. System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Path.GetFullPath(String path)
   at System.IO.DirectoryInfo..ctor(String path)
   at vstest.console.Internal.FilePatternParser.GetMatchingFiles(String filePattern) in /_/src/vstest.console/Internal/FilePatternParser.cs:line 81
   at Microsoft.VisualStudio.TestPlatform.CommandLine.CommandLineOptions.AddSource(String source) in /_/src/vstest.console/CommandLine/CommandLineOptions.cs:line 283
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Processors.ArgumentProcessorFactory.<>c__DisplayClass18_0.<WrapLazyProcessorToInitializeOnInstantiation>b__0() in /_/src/vstest.console/Processors/Utilities/ArgumentProcessorFactory.cs:line 282
   at System.Lazy`1.CreateValue()
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.GetArgumentProcessors(String[] args, List`1& processors) in /_/src/vstest.console/CommandLine/Executor.cs:line 283
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[] args) in /_/src/vstest.console/CommandLine/Executor.cs:line 173
   at Microsoft.VisualStudio.TestPlatform.CommandLine.Program.Main(String[] args) in /_/src/vstest.console/Program.cs:line 22

Exit code 134.
command: dotnet test **/*IntegrationTests.dll --logger "trx" -v "Normal" --results-directory "/home/vsts/work/r1/a"
```

**Comment by ricardofslp** [comment]
Hi @claasd,

Can you please try again in the newest version and let me know if it still happens and with the same error?

Thanks

**Comment by ricardofslp** [comment]
Hi @claasd ,

Any feedback on the newest version?

**Comment by ricardofslp** [comment]
Hi @MarcinFrankowski and  @timbarrass ,

Are you still having issues in the newest versions?

**Comment by neotrow** [comment]
i'm also having the same issue on the newest version. 

Can provide more feedback if needed.

**Comment by ricardofslp** [comment]
Hi @neotrow ,

Please do

**Comment by ricardofslp** [comment]
Hi @neotrow ,

May have found the issue. Please try with this: https://www.nuget.org/packages/dotnet-test-rerun/2.1.0-alpha.0

**Comment by ricardofslp** [comment]
Hi @timbarrass , @MarcinFrankowski , @neotrow , @claasd,

Could you check if you still have the same issue in the latest version?

**Comment by neotrow** [comment]
Sorry for the late reply. I will check it by the end of next week.

Thanks!

**Comment by neotrow** [comment]
@ricardofslp 

Sorry for the delay, but i'm happy to report that it's working with the latest version 🎉 

Many thanks!
